### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by northwestwitch** [Clinical-Genomics/preClinVar#46]
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/chiararasi/miniconda3/envs/preclinvar/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/chiararasi/miniconda3/envs/preclinvar/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/chiararasi/miniconda3/envs/preclinvar/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/chiararasi/miniconda3/envs/preclinvar/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/chiararasi/miniconda3/envs/preclinvar/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/chiararasi/miniconda3/envs/preclinvar/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/chiararasi/miniconda3/envs/preclinvar/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/Users/chiararasi/miniconda3/envs/preclinvar/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/Users/chiararasi/miniconda3/envs/preclinvar/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/chiararasi/miniconda3/envs/preclinvar/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/chiararasi/miniconda3/envs/preclinvar/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/Users/chiararasi/miniconda3/envs/preclinvar/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/Users/chiararasi/miniconda3/envs/preclinvar/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/Users/chiararasi/miniconda3/envs/preclinvar/lib/python3.8/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/Users/chiararasi/miniconda3/envs/preclinvar/lib/python3.8/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/chiararasi/Documents/work/GITs/preClinVar/./preClinVar/main.py", line 109, in csv_2_json
    submission_dict = csv_fields_to_submission(variants_lines, casedata_lines)
  File "/Users/chiararasi/Documents/work/GITs/preClinVar/./preClinVar/csv_parser.py", line 191, in csv_fields_to_submission
    set_item_assertion_criteria(item, line_dict)
  File "/Users/chiararasi/Documents/work/GITs/preClinVar/./preClinVar/csv_parser.py", line 18, in set_item_assertion_criteria
    if "PMID:" in asc:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by northwestwitch** [comment]
This is triggered by assertion criteria that was removed the the latest versions of the Variant CSV file.
